apiVersion: v1
kind: Namespace
metadata:
  name: sql
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: sql
type: Opaque
data:
  mysql-root-pass: b21hcjEyMzQ=  # base64('omar1234')
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: sql
  labels:
    app: todolist-app
    tier: database
spec:
  clusterIP: None           # Headless for StatefulSet
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: todolist-app
    tier: database
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fast
provisioner: docker.io/hostpath
volumeBindingMode: Immediate
parameters:
  type: pd-ssd
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-statefulset
  namespace: sql
  labels:
    app: todolist-app
    tier: database
spec:
  serviceName: mysql
  replicas: 1
  selector:
    matchLabels:
      app: todolist-app
      tier: database
  template:
    metadata:
      labels:
        app: todolist-app
        tier: database
    spec:
      containers:
        - name: mysql-container
          image: joselin721/database
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-root-pass
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: fast
        resources:
          requests:
            storage: 1Gi
