apiVersion: v1
kind: Namespace
metadata:
  name: sql
---
# MySQL Secret
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: sql
type: Opaque
data:
  mysql-root-pass: b21hcjEyMzQ=  # base64 for "omar1234"
---
# Persistent Volume (hostPath - Local Storage)
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/mysql
  persistentVolumeReclaimPolicy: Retain
---
# Persistent Volume Claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: sql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
# MySQL Service
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: sql
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: todolist-app
    tier: database
---
# MySQL StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-statefulset
  namespace: sql
  labels:
    app: todolist-app
    tier: database
spec:
  serviceName: mysql
  replicas: 1
  selector:
    matchLabels:
      app: todolist-app
      tier: database
  template:
    metadata:
      labels:
        app: todolist-app
        tier: database
    spec:
      containers:
        - name: mysql-container
          image: joselin721/database:latest
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-root-pass
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
