apiVersion: v1
kind: Namespace
metadata:
  name: backend
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: backend
type: Opaque
data:
  db-username: cm9vdA==       # base64('root')
  db-password: b21hcjEyMzQ=   # base64('omar1234')
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: backend
  labels:
    app: todolist-app
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todolist-app
      tier: backend
  template:
    metadata:
      labels:
        app: todolist-app
        tier: backend
    spec:
      containers:
        - name: backend-container
          image: joselin721/backend
          ports:
            - containerPort: 8081
          env:
            - name: DB_HOST
              value: "mysql.sql.svc.cluster.local"
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db-username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db-password
            - name: DB_NAME
              value: todolist
---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: backend
  labels:
    app: todolist-app
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: todolist-app
    tier: backend
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
