---
# -------------------------
# Backend Deployment
# -------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: todolist-app
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todolist-app
      tier: backend
  template:
    metadata:
      labels:
        app: todolist-app
        tier: backend
    spec:
      containers:
        - name: backend-container
          image: joselin721/backend
          ports:
            - containerPort: 8081
              name: webserver-port
---
# -------------------------
# Backend Service (ClusterIP only)
# -------------------------
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  labels:
    app: todolist-app
    tier: backend
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  selector:
    app: todolist-app
    tier: backend
