apiVersion: v1
kind: Namespace
metadata:
  name: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: frontend
  labels:
    app: todolist-app
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todolist-app
      tier: frontend
  template:
    metadata:
      labels:
        app: todolist-app
        tier: frontend
    spec:
      containers:
        - name: frontend-container
          image: joselin721/frontend:latest
          ports:
            - containerPort: 4173
          env:
            - name: VITE_BACKEND_URL
              value: http://backend-svc.backend.svc.cluster.local:8081
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: frontend
  labels:
    app: todolist-app
    tier: frontend
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 4173
      targetPort: 4173
      nodePort: 30000
  selector:
    app: todolist-app
    tier: frontend
